name: six_cash
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  shared_preferences: ^2.1.0
  connectivity_plus: ^3.0.6
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^14.0.0+1
  path_provider: ^2.0.14
  url_strategy: ^0.2.0
  dotted_border: ^2.0.0+3
  flutter_contacts: ^1.1.6
  azlistview: ^2.0.0
  pin_code_fields: ^7.4.0
  modal_bottom_sheet: ^2.1.2
  slide_to_confirm: ^1.1.0
  lottie: ^2.3.2
  expandable_bottom_sheet: ^1.1.1+1
  smooth_page_indicator: ^1.1.0
  image_picker: ^0.8.7+4
  country_code_picker: ^3.0.0
  camera: ^0.10.4
  http: ^0.13.6
  carousel_slider: ^4.2.1
  webview_flutter: ^4.2.0
  flutter_svg: ^2.0.5
  device_preview: ^1.1.0
  flutter_html: ^3.0.0-alpha.6
  shimmer: ^2.0.0
  permission_handler: ^10.2.0
  share_plus: ^4.5.3
  screenshot: ^2.1.0
  gallery_saver: ^2.3.2
  modal_progress_hud_nsn: ^0.4.0
  phone_number: ^1.0.0
  path_drawing: ^1.0.1
  local_auth: ^2.1.6
  google_mlkit_barcode_scanning: ^0.6.0
  google_mlkit_face_detection: ^0.6.0
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^8.0.0
  app_settings: ^4.2.0
  percent_indicator: ^4.2.3
  flutter_smart_dialog: ^4.9.0+6
  device_info_plus: ^8.2.2
  unique_identifier: ^0.3.0
  url_launcher: ^6.1.10


  flutter_inappwebview:
    git:
      url: https://github.com/Estrelio/flutter_inappwebview.git
      ref: fix-xcode-17

  #flutter_inappwebview: ^5.7.2+3
  scroll_to_index: ^3.0.1
  flutter_tts: ^3.8.3
  vibration: ^1.7.7


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/animationFile/
    - assets/payment/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Light.ttf
          weight: 300
        - asset: assets/font/Rubik-Regular.ttf
          weight: 400
        - asset: assets/font/Rubik-Medium.ttf
          weight: 500
        - asset: assets/font/Rubik-SemiBold.ttf
          weight: 600
